#!/bin/bash

INSTALL_DIR=/home/$USER/code/backup

backup_file() {
    if [ -f $1 ]; then
        cp $1 /home/$USER/tmp
    fi
}

# To be safe...
if [ ! -d "/home/$USER/tmp" ]; then
    mkdir /home/$USER/tmp
fi

backup_file /home/$USER/.bashrc
backup_file /home/$USER/.bash_aliases
backup_file /home/$USER/.bash_fns
backup_file /home/$USER/.tmux.conf

echo "Old files have been backed up to ~/tmp folder."

# Bash setup.
ln -sf $INSTALL_DIR/config/bashrc /home/$USER/.bashrc
ln -sf $INSTALL_DIR/config/bash_aliases /home/$USER/.bash_aliases
ln -sf $INSTALL_DIR/config/bash_fns /home/$USER/.bash_fns

# Check where Sublime is installed.
if [ -d "/home/$USER/.config/sublime-text" ]; then
    SUBLIME_DIR=/home/$USER/.config/sublime-text
elif [ -d "/home/$USER/.config/sublime-text-3" ]; then
    SUBLIME_DIR=/home/$USER/.config/sublime-text-3
fi

# Update Sublime Preferences, if installed.
if [[ ! -z "${SUBLIME_DIR}" ]]; then
    backup_file $SUBLIME_DIR/Packages/User/Anaconda.sublime-settings
    backup_file $SUBLIME_DIR/Packages/User/Preferences.sublime-settings

    ln -sf $INSTALL_DIR/config/Anaconda.sublime-settings $SUBLIME_DIR/Packages/User/Anaconda.sublime-settings
    ln -sf $INSTALL_DIR/config/Preferences.sublime-settings $SUBLIME_DIR/Packages/User/Preferences.sublime-settings

    echo "Sublime preferences updated in $SUBLIME_DIR"
else
    echo "No Sublime Text configuration found."
fi

# Tmux setup.
ln -sf $INSTALL_DIR/config/tmux.conf /home/$USER/.tmux.conf

# Apply changes to bash.
source /home/$USER/.bashrc

echo "Changes applied."
